/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author Leah
 */
public class PresentationUI extends javax.swing.JFrame {

    /**
     * Creates new form PresentationUI
     */
    public PresentationUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        presentation = new javax.swing.JPanel();
        lectureContentScroll = new javax.swing.JScrollPane();
        lectureContentViewer = new javax.swing.JTextPane();
        navigation = new javax.swing.JPanel();
        lectureSlideScroll = new javax.swing.JScrollPane();
        lectureSlideViewer = new javax.swing.JList();
        navigationTools = new javax.swing.JPanel();
        firstSlideButton = new javax.swing.JButton();
        previousSlideButton = new javax.swing.JButton();
        searchPage = new javax.swing.JTextField();
        nextSlideButton = new javax.swing.JButton();
        lastSlideButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(612, 445));

        presentation.setPreferredSize(new java.awt.Dimension(599, 204));

        lectureContentScroll.setViewportView(lectureContentViewer);

        javax.swing.GroupLayout presentationLayout = new javax.swing.GroupLayout(presentation);
        presentation.setLayout(presentationLayout);
        presentationLayout.setHorizontalGroup(
            presentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lectureContentScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        presentationLayout.setVerticalGroup(
            presentationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lectureContentScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        navigation.setPreferredSize(new java.awt.Dimension(599, 223));

        lectureSlideViewer.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Slide 1", "Slide 2", "Slide 3", "Slide 4", "Slide 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lectureSlideViewer.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lectureSlideViewer.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        lectureSlideViewer.setVisibleRowCount(1);
        lectureSlideScroll.setViewportView(lectureSlideViewer);

        navigationTools.setBackground(new java.awt.Color(0, 51, 102));
        navigationTools.setPreferredSize(new java.awt.Dimension(599, 55));

        firstSlideButton.setText("|<");
        firstSlideButton.setFocusable(false);
        firstSlideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstSlideButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        firstSlideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstSlideButtonActionPerformed(evt);
            }
        });

        previousSlideButton.setText("<");
        previousSlideButton.setFocusable(false);
        previousSlideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previousSlideButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        previousSlideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousSlideButtonActionPerformed(evt);
            }
        });

        searchPage.setText("Search by Page Number...");
        searchPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPageActionPerformed(evt);
            }
        });

        nextSlideButton.setText(">");
        nextSlideButton.setFocusable(false);
        nextSlideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nextSlideButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nextSlideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextSlideButtonActionPerformed(evt);
            }
        });

        lastSlideButton.setText(">|");
        lastSlideButton.setFocusable(false);
        lastSlideButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lastSlideButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lastSlideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastSlideButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationToolsLayout = new javax.swing.GroupLayout(navigationTools);
        navigationTools.setLayout(navigationToolsLayout);
        navigationToolsLayout.setHorizontalGroup(
            navigationToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstSlideButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(previousSlideButton)
                .addGap(112, 112, 112)
                .addComponent(searchPage, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(nextSlideButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastSlideButton)
                .addContainerGap())
        );
        navigationToolsLayout.setVerticalGroup(
            navigationToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationToolsLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(navigationToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchPage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextSlideButton)
                    .addComponent(lastSlideButton)
                    .addComponent(previousSlideButton)
                    .addComponent(firstSlideButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout navigationLayout = new javax.swing.GroupLayout(navigation);
        navigation.setLayout(navigationLayout);
        navigationLayout.setHorizontalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navigationTools, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lectureSlideScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        navigationLayout.setVerticalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(navigationTools, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lectureSlideScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(presentation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(presentation, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstSlideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstSlideButtonActionPerformed
        // TODO add your handling code here:
        lectureSlideViewer.setSelectedIndex(0);
        System.out.println("First Slide button pressed.");
    }//GEN-LAST:event_firstSlideButtonActionPerformed

    private void lastSlideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastSlideButtonActionPerformed
        // TODO add your handling code here:
        lectureSlideViewer.setSelectedIndex(4);
        System.out.println("Last Slide button pressed.");
    }//GEN-LAST:event_lastSlideButtonActionPerformed

    private void previousSlideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousSlideButtonActionPerformed
        // TODO add your handling code here:
        int currIndex = lectureSlideViewer.getSelectedIndex();
        if (currIndex > 0)
            lectureSlideViewer.setSelectedIndex(currIndex - 1);
        System.out.println("Previous Slide button pressed.");
    }//GEN-LAST:event_previousSlideButtonActionPerformed

    private void nextSlideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextSlideButtonActionPerformed
        // TODO add your handling code here:
        int currIndex = lectureSlideViewer.getSelectedIndex();
        if (currIndex < 4)
            lectureSlideViewer.setSelectedIndex(currIndex + 1);
        System.out.println("Next Slide button pressed.");
    }//GEN-LAST:event_nextSlideButtonActionPerformed

    private void searchPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPageActionPerformed
        // TODO add your handling code here:
        System.out.println("Entered page number to search for.");
    }//GEN-LAST:event_searchPageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresentationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresentationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresentationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresentationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresentationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstSlideButton;
    private javax.swing.JButton lastSlideButton;
    private javax.swing.JScrollPane lectureContentScroll;
    private javax.swing.JTextPane lectureContentViewer;
    private javax.swing.JScrollPane lectureSlideScroll;
    private javax.swing.JList lectureSlideViewer;
    private javax.swing.JPanel navigation;
    private javax.swing.JPanel navigationTools;
    private javax.swing.JButton nextSlideButton;
    private javax.swing.JPanel presentation;
    private javax.swing.JButton previousSlideButton;
    private javax.swing.JTextField searchPage;
    // End of variables declaration//GEN-END:variables
}
