/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roster;

/**
 *
 * @author Eric
 */
public class RosterUI extends javax.swing.JFrame {

    /**
     * Creates new form RosterUI
     */
    public RosterUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChatUI = new javax.swing.JPanel();
        markAllPanel = new javax.swing.JPanel();
        nameLabel = new java.awt.Label();
        canChatLabel = new java.awt.Label();
        canDrawLabel = new java.awt.Label();
        canAssignLabel = new java.awt.Label();
        markAllLabel = new java.awt.Label();
        canChatAllBox = new javax.swing.JCheckBox();
        canAssignAllBox = new javax.swing.JCheckBox();
        canDrawAllBox = new javax.swing.JCheckBox();
        importButton = new javax.swing.JButton();
        student1 = new javax.swing.JPanel();
        s1name = new javax.swing.JLabel();
        s1chat = new javax.swing.JCheckBox();
        s1draw = new javax.swing.JCheckBox();
        s1assign = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        student2 = new javax.swing.JPanel();
        s2name = new javax.swing.JLabel();
        s2chat = new javax.swing.JCheckBox();
        s2draw = new javax.swing.JCheckBox();
        s2assign = new javax.swing.JCheckBox();
        attended = new javax.swing.JButton();
        student3 = new javax.swing.JPanel();
        s3name = new javax.swing.JLabel();
        s3chat = new javax.swing.JCheckBox();
        s3draw = new javax.swing.JCheckBox();
        s3assign = new javax.swing.JCheckBox();
        attended1 = new javax.swing.JButton();
        student4 = new javax.swing.JPanel();
        s4label = new javax.swing.JLabel();
        s4chat = new javax.swing.JCheckBox();
        s4draw = new javax.swing.JCheckBox();
        s4assign = new javax.swing.JCheckBox();
        attended2 = new javax.swing.JButton();
        student5 = new javax.swing.JPanel();
        s5name = new javax.swing.JLabel();
        s5chat = new javax.swing.JCheckBox();
        s5draw = new javax.swing.JCheckBox();
        s5assign = new javax.swing.JCheckBox();
        attended3 = new javax.swing.JButton();
        student6 = new javax.swing.JPanel();
        s6name = new javax.swing.JLabel();
        s6chat = new javax.swing.JCheckBox();
        s6draw = new javax.swing.JCheckBox();
        s6assign = new javax.swing.JCheckBox();
        attended4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChatUI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ChatUI.setMaximumSize(new java.awt.Dimension(100, 100));

        markAllPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        markAllPanel.setMaximumSize(new java.awt.Dimension(100, 100));

        nameLabel.setText("Name: ");

        canChatLabel.setText("Can Chat:");

        canDrawLabel.setText("Can Draw:");

        canAssignLabel.setText("Can Assign:");

        markAllLabel.setName(""); // NOI18N
        markAllLabel.setText("Mark all:");

        canChatAllBox.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        canChatAllBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canChatAllBoxActionPerformed(evt);
            }
        });

        canAssignAllBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canAssignAllBoxActionPerformed(evt);
            }
        });

        canDrawAllBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        canDrawAllBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canDrawAllBoxActionPerformed(evt);
            }
        });

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout markAllPanelLayout = new javax.swing.GroupLayout(markAllPanel);
        markAllPanel.setLayout(markAllPanelLayout);
        markAllPanelLayout.setHorizontalGroup(
            markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markAllPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addComponent(markAllLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addComponent(canChatAllBox)
                        .addGap(22, 22, 22))
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(canChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(canDrawAllBox)
                        .addGap(82, 82, 82)
                        .addComponent(canAssignAllBox)
                        .addGap(46, 46, 46))
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(canDrawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(canAssignLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        markAllPanelLayout.setVerticalGroup(
            markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(markAllPanelLayout.createSequentialGroup()
                .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(canDrawLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canAssignLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(markAllPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(canChatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(markAllPanelLayout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(importButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(markAllPanelLayout.createSequentialGroup()
                        .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canDrawAllBox)
                            .addComponent(canAssignAllBox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, markAllPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(markAllPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(markAllLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(canChatAllBox, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        student1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s1name.setText("Carmen Dang");

        s1chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1chatActionPerformed(evt);
            }
        });

        s1draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1drawActionPerformed(evt);
            }
        });

        s1assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1assignActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/q.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout student1Layout = new javax.swing.GroupLayout(student1);
        student1.setLayout(student1Layout);
        student1Layout.setHorizontalGroup(
            student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(s1name)
                .addGap(66, 66, 66)
                .addComponent(s1chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s1draw)
                .addGap(80, 80, 80)
                .addComponent(s1assign)
                .addGap(46, 46, 46))
        );
        student1Layout.setVerticalGroup(
            student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(s1name)
                        .addComponent(s1chat)
                        .addComponent(s1assign)
                        .addComponent(s1draw)))
                .addGap(9, 9, 9))
        );

        student2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s2name.setText("Daniel Lee");

        s2chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2chatActionPerformed(evt);
            }
        });

        s2draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2drawActionPerformed(evt);
            }
        });

        s2assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2assignActionPerformed(evt);
            }
        });

        attended.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/gc.png"))); // NOI18N

        javax.swing.GroupLayout student2Layout = new javax.swing.GroupLayout(student2);
        student2.setLayout(student2Layout);
        student2Layout.setHorizontalGroup(
            student2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attended, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s2name)
                .addGap(82, 82, 82)
                .addComponent(s2chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s2draw)
                .addGap(84, 84, 84)
                .addComponent(s2assign)
                .addGap(44, 44, 44))
        );
        student2Layout.setVerticalGroup(
            student2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attended, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s2name)
                        .addComponent(s2chat)
                        .addComponent(s2draw)
                        .addComponent(s2assign)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        student3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s3name.setText("Eric Tran");

        s3chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3chatActionPerformed(evt);
            }
        });

        s3draw.setName(""); // NOI18N
        s3draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3drawActionPerformed(evt);
            }
        });

        s3assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3assignActionPerformed(evt);
            }
        });

        attended1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/gc.png"))); // NOI18N

        javax.swing.GroupLayout student3Layout = new javax.swing.GroupLayout(student3);
        student3.setLayout(student3Layout);
        student3Layout.setHorizontalGroup(
            student3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attended1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s3name)
                .addGap(88, 88, 88)
                .addComponent(s3chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s3draw)
                .addGap(84, 84, 84)
                .addComponent(s3assign)
                .addGap(43, 43, 43))
        );
        student3Layout.setVerticalGroup(
            student3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(student3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attended1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s3name)
                    .addGroup(student3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(student3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(s3chat)
                            .addComponent(s3draw)
                            .addComponent(s3assign))))
                .addContainerGap())
        );

        student4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s4label.setText("Jordan Tang");

        s4chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4chatActionPerformed(evt);
            }
        });

        s4draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4drawActionPerformed(evt);
            }
        });

        s4assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4assignActionPerformed(evt);
            }
        });

        attended2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/gc.png"))); // NOI18N

        javax.swing.GroupLayout student4Layout = new javax.swing.GroupLayout(student4);
        student4.setLayout(student4Layout);
        student4Layout.setHorizontalGroup(
            student4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attended2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s4label)
                .addGap(72, 72, 72)
                .addComponent(s4chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s4draw)
                .addGap(82, 82, 82)
                .addComponent(s4assign)
                .addGap(43, 43, 43))
        );
        student4Layout.setVerticalGroup(
            student4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(student4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attended2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s4label)
                        .addComponent(s4chat)
                        .addComponent(s4draw)
                        .addComponent(s4assign)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        student5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s5name.setText("Leah Pichay");

        s5chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5chatActionPerformed(evt);
            }
        });

        s5draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5drawActionPerformed(evt);
            }
        });

        s5assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5assignActionPerformed(evt);
            }
        });

        attended3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/gc.png"))); // NOI18N

        javax.swing.GroupLayout student5Layout = new javax.swing.GroupLayout(student5);
        student5.setLayout(student5Layout);
        student5Layout.setHorizontalGroup(
            student5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attended3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s5name)
                .addGap(71, 71, 71)
                .addComponent(s5chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s5draw)
                .addGap(83, 83, 83)
                .addComponent(s5assign)
                .addGap(44, 44, 44))
        );
        student5Layout.setVerticalGroup(
            student5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(student5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attended3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(student5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(s5chat)
                        .addComponent(s5draw)
                        .addComponent(s5assign)
                        .addComponent(s5name)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        student6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        s6name.setText("Tammy Kong");

        s6chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6chatActionPerformed(evt);
            }
        });

        s6draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6drawActionPerformed(evt);
            }
        });

        s6assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6assignActionPerformed(evt);
            }
        });

        attended4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/roster/gc.png"))); // NOI18N

        javax.swing.GroupLayout student6Layout = new javax.swing.GroupLayout(student6);
        student6.setLayout(student6Layout);
        student6Layout.setHorizontalGroup(
            student6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(attended4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s6name)
                .addGap(67, 67, 67)
                .addComponent(s6chat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s6draw)
                .addGap(78, 78, 78)
                .addComponent(s6assign)
                .addGap(45, 45, 45))
        );
        student6Layout.setVerticalGroup(
            student6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student6Layout.createSequentialGroup()
                .addGroup(student6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(student6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(student6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s6draw)
                            .addComponent(s6assign)
                            .addComponent(s6chat, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(s6name, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(student6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(attended4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ChatUILayout = new javax.swing.GroupLayout(ChatUI);
        ChatUI.setLayout(ChatUILayout);
        ChatUILayout.setHorizontalGroup(
            ChatUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatUILayout.createSequentialGroup()
                .addGroup(ChatUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(markAllPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(student6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        ChatUILayout.setVerticalGroup(
            ChatUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatUILayout.createSequentialGroup()
                .addComponent(markAllPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(student1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(student2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(student3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(student4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(student5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(student6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChatUI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ChatUI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void canDrawAllBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canDrawAllBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("Mark all: Can Draw pressed.");
        boolean canDrawAll = canDrawAllBox.isSelected();
        s1draw.setSelected(canDrawAll);
        s2draw.setSelected(canDrawAll);
        s3draw.setSelected(canDrawAll);
        s4draw.setSelected(canDrawAll);
        s5draw.setSelected(canDrawAll);
        s6draw.setSelected(canDrawAll);
    }//GEN-LAST:event_canDrawAllBoxActionPerformed

    private void canAssignAllBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canAssignAllBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("Mark all: Can Assign pressed.");
        boolean canAssignAll = canAssignAllBox.isSelected();
        s1assign.setSelected(canAssignAll);
        s2assign.setSelected(canAssignAll);
        s3assign.setSelected(canAssignAll);
        s4assign.setSelected(canAssignAll);
        s5assign.setSelected(canAssignAll);
        s6assign.setSelected(canAssignAll);
    }//GEN-LAST:event_canAssignAllBoxActionPerformed

    private void canChatAllBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canChatAllBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("Mark all: Can Chat pressed.");
        boolean canChatAll = canChatAllBox.isSelected();
        s1chat.setSelected(canChatAll);
        s2chat.setSelected(canChatAll);
        s3chat.setSelected(canChatAll);
        s4chat.setSelected(canChatAll);
        s5chat.setSelected(canChatAll);
        s6chat.setSelected(canChatAll);
    }//GEN-LAST:event_canChatAllBoxActionPerformed

    private void s1chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 1 Can Chat pressed.");
    }//GEN-LAST:event_s1chatActionPerformed

    private void s1drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 1 Can Draw pressed.");
    }//GEN-LAST:event_s1drawActionPerformed

    private void s1assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 1 Can Assign pressed.");
    }//GEN-LAST:event_s1assignActionPerformed

    private void s2chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 2 Can Chat pressed.");
    }//GEN-LAST:event_s2chatActionPerformed

    private void s2drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 2 Can Draw pressed.");
    }//GEN-LAST:event_s2drawActionPerformed

    private void s2assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 2 Can Assign pressed.");
    }//GEN-LAST:event_s2assignActionPerformed

    private void s3chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 3 Can Chat pressed.");
    }//GEN-LAST:event_s3chatActionPerformed

    private void s3drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 3 Can Draw pressed.");
    }//GEN-LAST:event_s3drawActionPerformed

    private void s3assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 3 Can Assign pressed.");
    }//GEN-LAST:event_s3assignActionPerformed

    private void s4chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 4 Can Chat pressed.");
    }//GEN-LAST:event_s4chatActionPerformed

    private void s4drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 4 Can Draw pressed.");
    }//GEN-LAST:event_s4drawActionPerformed

    private void s4assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 4 Can Assign pressed.");
    }//GEN-LAST:event_s4assignActionPerformed

    private void s5chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 5 Can Chat pressed.");
    }//GEN-LAST:event_s5chatActionPerformed

    private void s5drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 5 Can Draw pressed.");
    }//GEN-LAST:event_s5drawActionPerformed

    private void s5assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 5 Can Assign pressed.");
    }//GEN-LAST:event_s5assignActionPerformed

    private void s6chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6chatActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 6 Can Chat pressed.");
    }//GEN-LAST:event_s6chatActionPerformed

    private void s6drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6drawActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 6 Can Draw pressed.");
    }//GEN-LAST:event_s6drawActionPerformed

    private void s6assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6assignActionPerformed
        // TODO add your handling code here:
        System.out.println("Student 6 Can Assign pressed.");
    }//GEN-LAST:event_s6assignActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Import button was pressed.");
        ImportDialog importBox = new ImportDialog();
        importBox.setVisible(true);
        importBox.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_importButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.out.println("Question mark clicked. ");
        QuestionDialog questionDiag = new QuestionDialog();
        questionDiag.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RosterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RosterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RosterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RosterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RosterUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChatUI;
    private javax.swing.JButton attended;
    private javax.swing.JButton attended1;
    private javax.swing.JButton attended2;
    private javax.swing.JButton attended3;
    private javax.swing.JButton attended4;
    private javax.swing.JCheckBox canAssignAllBox;
    private java.awt.Label canAssignLabel;
    private javax.swing.JCheckBox canChatAllBox;
    private java.awt.Label canChatLabel;
    private javax.swing.JCheckBox canDrawAllBox;
    private java.awt.Label canDrawLabel;
    private javax.swing.JButton importButton;
    private javax.swing.JButton jButton2;
    private java.awt.Label markAllLabel;
    private javax.swing.JPanel markAllPanel;
    private java.awt.Label nameLabel;
    private javax.swing.JCheckBox s1assign;
    private javax.swing.JCheckBox s1chat;
    private javax.swing.JCheckBox s1draw;
    private javax.swing.JLabel s1name;
    private javax.swing.JCheckBox s2assign;
    private javax.swing.JCheckBox s2chat;
    private javax.swing.JCheckBox s2draw;
    private javax.swing.JLabel s2name;
    private javax.swing.JCheckBox s3assign;
    private javax.swing.JCheckBox s3chat;
    private javax.swing.JCheckBox s3draw;
    private javax.swing.JLabel s3name;
    private javax.swing.JCheckBox s4assign;
    private javax.swing.JCheckBox s4chat;
    private javax.swing.JCheckBox s4draw;
    private javax.swing.JLabel s4label;
    private javax.swing.JCheckBox s5assign;
    private javax.swing.JCheckBox s5chat;
    private javax.swing.JCheckBox s5draw;
    private javax.swing.JLabel s5name;
    private javax.swing.JCheckBox s6assign;
    private javax.swing.JCheckBox s6chat;
    private javax.swing.JCheckBox s6draw;
    private javax.swing.JLabel s6name;
    private javax.swing.JPanel student1;
    private javax.swing.JPanel student2;
    private javax.swing.JPanel student3;
    private javax.swing.JPanel student4;
    private javax.swing.JPanel student5;
    private javax.swing.JPanel student6;
    // End of variables declaration//GEN-END:variables
}
