/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eclasstool.view.presentation;

import javax.swing.DefaultListModel;
import static javax.swing.WindowConstants.HIDE_ON_CLOSE;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.util.*;
import eclasstool.model.presentation.*;
import eclasstool.model.layers.*;
/**
 *
 * @author Tammy Kong (takong@calpoly.edu)
 * @author Jordan Tang (jtang22@calpoly.edu)
 */
public class SlideManagerUI extends javax.swing.JInternalFrame {
    /**
     * Model for the slide manager
     */
    private DefaultListModel model;
    /**
     * Presentation lecture object
     */
    private Presentation lecture;
    
    private LayersManager layersManager;
    private PresentationUI presentUI;
    //private ArrayList<Slide> slides;
    private boolean canEdit;
    /**
     * Creates new form SlideManagerUI
     */
    public SlideManagerUI(LayersManager layersManager, PresentationUI ui, boolean canEdit) {
	    super("Slide Manager", false, true);
    	this.layersManager = layersManager;
        presentUI = ui;
        initComponents();
        initSlides();
        model.addElement("Slide " + (model.getSize() + 1));
        this.canEdit = false;
    }
    /**
     * Initialize the presentation and view
     */
    private void initSlides() {
        model = new DefaultListModel();
        lecture = new Presentation();
        lecture.add(new Slide(layersManager));
        slideList.setModel(model);
        /*model.addElement("Slide 1");
        slideList.setSelectedIndex(0);*/

        slideList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    //System.out.println(model.get(slideList.getSelectedIndex()) + " selected.");
                }
            }
        });
        
        slideList.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if(evt.getClickCount() == 2) {
                    final HTMLSlideUI html = new HTMLSlideUI();
                    html.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                            //presentUI.addText(this.getHTMLText());
                            int selectedNdx = slideList.getSelectedIndex();
                            //slides.get(selectedNdx).addText(html.getHTMLText());
                            html.dispose();
                        }
                    });
                    html.setVisible(true);
                    // slide.setLocationRelativeTo(SlideManagerUI.this);
                    html.setDefaultCloseOperation(HIDE_ON_CLOSE);    
                }
            }
        });
        slideList.setSelectedIndex(0);
        //slides = new ArrayList<Slide>();
    }
    
    /**
     * Getter method for boolean variable canEdit.
     * @return Returns the instance variable canEdit.
     */
    public boolean getCanEdit()  {
    	return canEdit;
    }
    
    /**
     * Sets the boolean instance variable canEdit.
     * @param b Boolean to set the variable to.
     */
    public void setCanEdit(boolean b)  {
    	canEdit = b;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        htmlButton = new javax.swing.JButton();
        addSlide = new javax.swing.JButton();
        deleteSlide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        slideScroll = new javax.swing.JScrollPane();
        slideList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        htmlButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        htmlButton.setText("HTML");
        htmlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                htmlButtonActionPerformed(evt);
            }
        });

        addSlide.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("eclasstool/view/presentation/add.png"))); // NOI18N
        addSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSlideActionPerformed(evt);
            }
        });

        deleteSlide.setIcon(new javax.swing.ImageIcon(getClass().getClassLoader().getResource("eclasstool/view/presentation/delete.png"))); // NOI18N
        deleteSlide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSlideActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Chapter 1: Presentation 1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(htmlButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addSlide)
                            .addComponent(deleteSlide)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(htmlButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5))
        );

        slideList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        slideList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = new String[0];
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        slideScroll.setViewportView(slideList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slideScroll)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(slideScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Adds a slide to the presentation
     * @param evt - event that occurred to invoke method
     */
    private void addSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSlideActionPerformed
        // TODO add your handling code here:
        model.addElement("Slide " + (model.getSize() + 1));
        presentUI.addSlide();
        //slides.add(new Slide(layersManager));
        //lecture.add(new Slide(layersManager));
    }//GEN-LAST:event_addSlideActionPerformed
    /**
     * Deletes a slide from the presentation
     * @param evt - event that occurred to invoke method
     */
    private void deleteSlideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSlideActionPerformed
        // TODO add your handling code here:
        int index = slideList.getSelectedIndex();
        if(index > -1)
        {
            //lecture.delete(index);
            //slides.remove(index);
        	for(int ndx = index + 1; ndx < model.size(); ndx++)  {
        		model.setElementAt("Slide " + ndx, ndx);
        	}
            model.removeElementAt(index);
            presentUI.deleteSlide(index);
            
        }
    }//GEN-LAST:event_deleteSlideActionPerformed
    /**
     * Opens the HTML editor for the presentation
     * @param evt - even that occurred to invoke method
     */
    private void htmlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_htmlButtonActionPerformed
        // TODO add your handling code here:
        final HTMLSlideUI html = new HTMLSlideUI();
        html.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                //presentUI.addText(this.getHTMLText());
                int selectedNdx = slideList.getSelectedIndex();
                presentUI.editSlide(selectedNdx, html.getHTMLText());
                //slides.get(selectedNdx).addText(html.getHTMLText());
                html.dispose();
            }
        });
        html.setVisible(true);
        html.setLocationRelativeTo(this);
        html.setDefaultCloseOperation(HIDE_ON_CLOSE);
    }//GEN-LAST:event_htmlButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Button to add a slide
     */
    private javax.swing.JButton addSlide;
    /**
     * Button to delete a slide
     */
    private javax.swing.JButton deleteSlide;
    /**
     * Button to bring up HTML editor
     */
    private javax.swing.JButton htmlButton;
    /**
     * Label for slide
     */
    private javax.swing.JLabel jLabel1;
    /**
     * Label for name
     */ 
    private javax.swing.JPanel jPanel1;
    /**
     * slide list for list of slides
     */
    private javax.swing.JList slideList;
    /**
     * Scroll pane for list
     */
    private javax.swing.JScrollPane slideScroll;
    // End of variables declaration//GEN-END:variables
}
