/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eclasstool.view.taskbar;

import eclasstool.model.chat.RemoteChat;
import eclasstool.model.layers.LayersManager;
import eclasstool.model.presentation.*;
import eclasstool.view.chat.ChatUI;
import eclasstool.view.drawingtools.DrawingToolsUI;
import eclasstool.view.layers.LayerManagerUI;
import eclasstool.view.presentation.PresentationUI;
import eclasstool.view.presentation.SlideManagerUI;
import eclasstool.view.roster.RosterUI;
import eclasstool.view.filemanager.FileManagerUI;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Leah
 */
public class ClassroomUI extends javax.swing.JFrame {
    /**
     * Graphical component for ChatUI.
     */
    private ChatUI chatUI;
    /**
     * Graphical component for RosterUI.
     */
    private RosterUI rosterUI;
    
    /**
     * Graphical component for FileManagerUI.
     */  
    private FileManagerUI fileManagerUI;
    /**
     * Graphical component for SlideManagerUI.
     */
    private SlideManagerUI lectureEditorUI;
    /**
     * Graphical component for PresentationUI.
     */
    private PresentationUI presentUI;
    /**
     * Graphical component for LayersManagerUI.
     */
    private LayerManagerUI layersUI;
    /**
     * Graphical component for DrawingToolsUI.
     */
    private DrawingToolsUI drawingUI;
    
    /**
     * Creates new form ClassroomUI
     */
    public ClassroomUI(String name, RosterUI roster, RemoteChat stub) {
        initComponents();
        
        Dimension desktopSize = this.getSize();
        Dimension internalSize = taskbar.getSize();
        
        //taskbar.setLocation((desktopSize.width - internalSize.width)/2,
        //    (desktopSize.height - internalSize.height * 2));
        classroom.setOpaque(true);
        add(classroom, BorderLayout.CENTER);
        add(taskbar, BorderLayout.SOUTH);
        
        chatUI = new ChatUI(name, stub);
        rosterUI = roster;
        //fileManagerUI = new FileManager();
        //fileManagerUI.setVisible(true);
        drawingUI = new DrawingToolsUI();
        layersUI = new LayerManagerUI(drawingUI);
        
        LayersManager layers = layersUI.getLayersManager();
        Presentation presentation = new Presentation(); 
        for (int ndx = 0; ndx < 1; ndx++)
        {
            presentation.add(new Slide(layers));
        }
        presentUI = new PresentationUI(presentation, drawingUI, layersUI);
        
        lectureEditorUI = new SlideManagerUI(layers, presentUI, false);
       
        fileManagerUI = new FileManagerUI(presentUI, lectureEditorUI, layers);
        
        classroom.add(chatUI);
        classroom.add(rosterUI);
        classroom.add(fileManagerUI);
        classroom.add(drawingUI);
        classroom.add(layersUI);
        classroom.add(lectureEditorUI);
        classroom.add(presentUI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskbar = new javax.swing.JPanel();
        drawingTools = new javax.swing.JButton();
        lectureEditor = new javax.swing.JButton();
        roster = new javax.swing.JButton();
        presentViewer = new javax.swing.JButton();
        layersManager = new javax.swing.JButton();
        chat = new javax.swing.JButton();
        fileManager = new javax.swing.JButton();
        classroom = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 730));

        taskbar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        taskbar.setPreferredSize(new java.awt.Dimension(650, 50));

        drawingTools.setText("drawing");
        drawingTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawingToolsActionPerformed(evt);
            }
        });

        lectureEditor.setText("editor");
        lectureEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(lectureEditorUI.getCanEdit() == true)
                {
                    lectureEditorActionPerformed(evt);
                }
            }
        });

        roster.setText("roster");
        roster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rosterActionPerformed(evt);
            }
        });

        presentViewer.setText("present");
        presentViewer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentViewerActionPerformed(evt);
            }
        });

        layersManager.setText("layers");
        layersManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layersManagerActionPerformed(evt);
            }
        });

        chat.setText("chat");
        chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatActionPerformed(evt);
            }
        });

        fileManager.setText("files");
        fileManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileManagerActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout taskbarLayout = new javax.swing.GroupLayout(taskbar);
        taskbar.setLayout(taskbarLayout);
        taskbarLayout.setHorizontalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawingTools)
                .addGap(18, 18, 18)
                .addComponent(lectureEditor)
                .addGap(18, 18, 18)
                .addComponent(roster)
                .addGap(18, 18, 18)
                .addComponent(presentViewer)
                .addGap(18, 18, 18)
                .addComponent(layersManager)
                .addGap(18, 18, 18)
                .addComponent(chat)
                .addGap(18, 18, 18)
                .addComponent(fileManager)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        taskbarLayout.setVerticalGroup(
            taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taskbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(drawingTools, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lectureEditor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presentViewer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(layersManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        classroom.setMaximumSize(new java.awt.Dimension(1280, 800));
        classroom.setMinimumSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout classroomLayout = new javax.swing.GroupLayout(classroom);
        classroom.setLayout(classroomLayout);
        classroomLayout.setHorizontalGroup(
            classroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        classroomLayout.setVerticalGroup(
            classroomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 694, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(taskbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(classroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(classroom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rosterActionPerformed
        // TODO add your handling code here:
        rosterUI.setVisible(true);
        // rosterUI.setLocationRelativeTo(this);
        rosterUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        rosterUI.setResizable(false);
    }//GEN-LAST:event_rosterActionPerformed

    private void layersManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layersManagerActionPerformed
        // TODO add your handling code here:
        layersUI.setVisible(true);
        // layersUI.setLocationRelativeTo(this);
        layersUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        layersUI.setResizable(false);
    }//GEN-LAST:event_layersManagerActionPerformed

    private void drawingToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawingToolsActionPerformed
        // TODO add your handling code here:
        drawingUI.setVisible(true);
        // drawingUI.setLocationRelativeTo(this);
        drawingUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        drawingUI.setResizable(false);
    }//GEN-LAST:event_drawingToolsActionPerformed

    private void lectureEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lectureEditorActionPerformed
        // TODO add your handling code here:
        lectureEditorUI.setVisible(true);
        // lectureEditorUI.setLocationRelativeTo(this);
        lectureEditorUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        lectureEditorUI.setResizable(false);
    }//GEN-LAST:event_lectureEditorActionPerformed

    private void presentViewerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentViewerActionPerformed
        // TODO add your handling code here:
        presentUI.setVisible(true);
        // presentUI.setLocationRelativeTo(this);
        presentUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        presentUI.setResizable(false);
    }//GEN-LAST:event_presentViewerActionPerformed

    private void chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatActionPerformed
        // TODO add your handling code here:
        chatUI.setVisible(true);
        // chatUI.setLocationRelativeTo(this);
        chatUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        chatUI.setResizable(false);
    }//GEN-LAST:event_chatActionPerformed

    private void fileManagerActionPerformed(java.awt.event.ActionEvent evt) {
        fileManagerUI.setVisible(true);
        fileManagerUI.setDefaultCloseOperation(HIDE_ON_CLOSE);
        fileManagerUI.setResizable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chat;
    private javax.swing.JDesktopPane classroom;
    private javax.swing.JButton drawingTools;
    private javax.swing.JButton fileManager;
    private javax.swing.JButton layersManager;
    private javax.swing.JButton lectureEditor;
    private javax.swing.JButton presentViewer;
    private javax.swing.JButton roster;
    private javax.swing.JPanel taskbar;
    // End of variables declaration//GEN-END:variables
}
