/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * @author Daniel Lee (dlee104@calpoly.edu)
 */
package eclasstool.view.chat;

import eclasstool.model.chat.*;

/**
 * AskQuestionDialog models a graphical user interface for
 * asking a question privately or publically. It receives
 * user input and sends the question over to the roster 
 * for pending answer.
 *
 * @author Daniel Lee
 */
public class AskQuestionDialog extends javax.swing.JFrame {

    /**
     * Constructs a new ask question dialog.
     */
    public AskQuestionDialog(Chat chat) {
        forAll = true;
        this.chat = chat;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        QuestionText = new javax.swing.JTextPane();
        ToLabel = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        AllRadio = new javax.swing.JRadioButton();
        InstructorRadio = new javax.swing.JRadioButton();

        QuestionText.setText("Enter Question...");
        jScrollPane2.setViewportView(QuestionText);

        ToLabel.setText("To:");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        buttonGroup1.add(AllRadio);
        AllRadio.setSelected(true);
        AllRadio.setText("All");
        AllRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(InstructorRadio);
        InstructorRadio.setText("Instructor Only");
        InstructorRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructorRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ToLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AllRadio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InstructorRadio))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AllRadio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(ToLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InstructorRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Submit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Callback function for Public radio button press.
     */
    private void AllRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRadioActionPerformed
        // TODO add your handling code here:
        forAll = true;
    }//GEN-LAST:event_AllRadioActionPerformed

    /**
     * Callback function for Private radio button press.
     */
    private void InstructorRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructorRadioActionPerformed
        // TODO add your handling code here:
        forAll = false;
    }//GEN-LAST:event_InstructorRadioActionPerformed

    /**
     * Callback function for submitting dialog.
     */
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        chat.askQuestion(QuestionText.getText());
        System.out.println("forAll? " + forAll);
        this.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * Callback function for cancelling dialog.
     */
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    /**
     * Checks for question privacy.
     */
    private boolean forAll;
    /**
     * Chat model for chat functionality.
     */
    private Chat chat;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /**
     * Public question option.
     */
    private javax.swing.JRadioButton AllRadio;
    /**
     * Cancel question button.
     */
    private javax.swing.JButton Cancel;
    /**
     * Private question option.
     */
    private javax.swing.JRadioButton InstructorRadio;
    /**
     * User input field for question.
     */
    private javax.swing.JTextPane QuestionText;
    /**
     * Submit question button.
     */
    private javax.swing.JButton Submit;
    /**
     * To: label.
     */
    private javax.swing.JLabel ToLabel;
    /**
     * Button group for question privacy options.
     */
    private javax.swing.ButtonGroup buttonGroup1;
    /**
     * Simple scroll pane for question dialog.
     */
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
