/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Daniel Lee
 */
public class ChatUI extends javax.swing.JFrame {
    private DefaultListModel model;

    /**
     * Creates new form Chatbox
     */
    public ChatUI() {
        initComponents();
        initChatrooms();
        initChatButtons();
    }
    
    private void initChatrooms() {
        model = new DefaultListModel();
        ChatroomsList.setModel(model);
        model.addElement("Classroom");
        ChatroomsList.setSelectedIndex(0);
        
        ChatroomsList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    System.out.println(model.get(ChatroomsList.getSelectedIndex()) + " pressed.");
                }
            }
        });
    }
    
    private void initChatButtons() {
        AddUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserDialog addDialog = new AddUserDialog();
                addDialog.setVisible(true);
                addDialog.setLocationRelativeTo(ChatUI.this);
                addDialog.setDefaultCloseOperation(HIDE_ON_CLOSE);
                addDialog.setResizable(false);
            }
        });
        
        ViewUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("View Users pressed.");
            }
        });
        
        LeaveChatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                System.out.println("Leave Chatroom pressed.");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChatPanel = new javax.swing.JPanel();
        CommentPanel = new javax.swing.JScrollPane();
        Comments = new javax.swing.JTextArea();
        CommentField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        AddUsersButton = new javax.swing.JButton();
        ViewUsersButton = new javax.swing.JButton();
        LeaveChatButton = new javax.swing.JButton();
        NewChatButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChatroomsList = new javax.swing.JList();
        AskQuestion = new javax.swing.JButton();

        ChatPanel.setBackground(new java.awt.Color(102, 102, 102));

        CommentPanel.setBackground(new java.awt.Color(255, 255, 255));
        CommentPanel.setBorder(null);
        CommentPanel.setViewportBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Comments.setColumns(20);
        Comments.setLineWrap(true);
        Comments.setRows(5);
        Comments.setBorder(null);
        CommentPanel.setViewportView(Comments);

        CommentField.setText("Comment...");
        CommentField.setToolTipText("Add Comment...");
        CommentField.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CommentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentFieldActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), null));

        AddUsersButton.setText("+");

        ViewUsersButton.setText("Users");

        LeaveChatButton.setText("Leave");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddUsersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewUsersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(LeaveChatButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddUsersButton)
                    .addComponent(ViewUsersButton)
                    .addComponent(LeaveChatButton))
                .addContainerGap())
        );

        NewChatButton.setText("New Chat");
        NewChatButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        NewChatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewChatButtonActionPerformed(evt);
            }
        });

        ChatroomsList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ChatroomsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(ChatroomsList);

        AskQuestion.setText("Ask Question");
        AskQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AskQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChatPanelLayout = new javax.swing.GroupLayout(ChatPanel);
        ChatPanel.setLayout(ChatPanelLayout);
        ChatPanelLayout.setHorizontalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChatPanelLayout.createSequentialGroup()
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(NewChatButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(AskQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CommentField)
                    .addComponent(CommentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        ChatPanelLayout.setVerticalGroup(
            ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChatPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ChatPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(AskQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NewChatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ChatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChatPanelLayout.createSequentialGroup()
                        .addComponent(CommentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(CommentField, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(ChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(ChatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void CommentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentFieldActionPerformed
        // TODO add your handling code here:
        Comments.append("User: " + CommentField.getText() + "\n");
    }//GEN-LAST:event_CommentFieldActionPerformed

    private void NewChatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewChatButtonActionPerformed

        System.out.println("New Chat pressed.");
        model.addElement("Chatroom " + (model.getSize() + 1));
    }//GEN-LAST:event_NewChatButtonActionPerformed

    private void AskQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AskQuestionActionPerformed
        // TODO add your handling code here:
        AskQuestionDialog question = new AskQuestionDialog();
        question.setVisible(true);
        question.setLocationRelativeTo(this);
        question.setDefaultCloseOperation(HIDE_ON_CLOSE);
        question.setResizable(false);
    }//GEN-LAST:event_AskQuestionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUsersButton;
    private javax.swing.JButton AskQuestion;
    private javax.swing.JPanel ChatPanel;
    private javax.swing.JList ChatroomsList;
    private javax.swing.JTextField CommentField;
    private javax.swing.JScrollPane CommentPanel;
    private javax.swing.JTextArea Comments;
    private javax.swing.JButton LeaveChatButton;
    private javax.swing.JButton NewChatButton;
    private javax.swing.JButton ViewUsersButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
